# Generated by Django 4.2 on 2024-04-23 12:53

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        # migrations.RemoveField(
        #     model_name='record',
        #     name='address',
        # ),
        # migrations.RemoveField(
        #     model_name='record',
        #     name='city',
        # ),
        # migrations.RemoveField(
        #     model_name='record',
        #     name='country',
        # ),
        migrations.RemoveField(
            model_name='record',
            name='phone',
        ),
        # migrations.RemoveField(
        #     model_name='record',
        #     name='province',
        # ),
        migrations.AddField(
            model_name='record',
            name='password',
            field=models.CharField(default=django.utils.timezone.now, max_length=15),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='record',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
