# Generated by Django 4.2 on 2024-04-23 13:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_remove_record_address_remove_record_city_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='phone',
            field=models.CharField(default=django.utils.timezone.now, max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='record',
            name='email',
            field=models.EmailField(max_length=255),
        ),
        migrations.AlterField(
            model_name='record',
            name='password',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='record',
            name='username',
            field=models.CharField(max_length=255),
        ),
    ]
